# Generated by Django 3.1.2 on 2021-03-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210227_1651'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='web_member',
        ),
    ]
